# Generated by Django 3.1.2 on 2020-10-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'setting up...'), (2, 'running'), (3, 'completed'), (4, 'failed')], db_index=True)),
                ('signature', models.CharField(db_index=True, max_length=255)),
                ('sleep_time', models.IntegerField(null=True)),
                ('thread_id', models.IntegerField(null=True)),
                ('action_date', models.DateTimeField()),
                ('return_address', models.CharField(max_length=255)),
            ],
        ),
    ]
