# Generated by Django 3.1.2 on 2020-10-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='param',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='timer',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'setting up...'), (2, 'running'), (3, 'completed'), (4, 'failed'), (5, 'stopped')], db_index=True),
        ),
    ]
