# Generated by Django 3.1.2 on 2020-10-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0002_auto_20201024_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='param',
            field=models.TextField(default='', null=True),
        ),
    ]
