# Generated by Django 3.1.2 on 2020-10-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0003_auto_20201024_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='thread_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
