# Generated by Django 3.1.2 on 2020-10-23 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('week_value', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='interval',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customers.interval'),
        ),
    ]
