# Generated by Django 3.1.2 on 2020-10-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_target_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='status',
            field=models.IntegerField(choices=[(0, 'has not scheduled'), (1, 'scheduled'), (2, 'completed'), (3, 'failed')], db_index=True, default=0),
        ),
    ]
