# Generated by Django 3.1.2 on 2020-10-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20201024_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='signature',
            field=models.CharField(db_index=True, default='6176a2883e48434184964a07d320ece0', max_length=255),
        ),
        migrations.AlterField(
            model_name='target',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'completed'), (2, 'failed')], db_index=True, default=0),
        ),
    ]
