# Generated by Django 3.1.2 on 2020-10-25 00:44
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20201024_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='future_sending',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='customer',
            name='signature',
            field=models.CharField(db_index=True, default='24d74e6dcd374e0b8255c7f89ca428f9', max_length=255),
        ),
    ]
