# Generated by Django 3.1.2 on 2020-10-25 00:45
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20201025_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='future_sending',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='customer',
            name='signature',
            field=models.CharField(db_index=True, default='85fd556d1d5648f68329ec65a73b7cff', max_length=255),
        ),
    ]
