# Generated by Django 3.1.2 on 2020-10-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20201025_0045'),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='customer',
    #         old_name='futre_sending',
    #         new_name='future_sending',
    #     ),
    #     migrations.AlterField(
    #         model_name='customer',
    #         name='signature',
    #         field=models.CharField(db_index=True, default='52d0683b2a7b47aea02281226f776ae2', max_length=255),
    #     ),
    # ]
