# Generated by Django 3.1.2 on 2020-10-25 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20201025_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='future_sending',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 0, 47, 50, 558733), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='signature',
            field=models.CharField(db_index=True, default='b7faa8dcdba84a28832402b335631956', max_length=255),
        ),
    ]
