# Generated by Django 3.1.2 on 2020-10-25 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20201025_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='future_sending',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='signature',
            field=models.CharField(db_index=True, default='d3e9a23e4262450b95900a1d54c39040', max_length=255),
        ),
    ]
