# Generated by Django 3.1.2 on 2020-10-25 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20201025_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='future_sending',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='customer',
            name='signature',
            field=models.CharField(db_index=True, default='dfe1630cf15c48ec941898c8c6e1f900', max_length=255),
        ),
    ]
