# Generated by Django 3.1.2 on 2020-10-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_auto_20201025_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='signature',
            field=models.CharField(db_index=True, default='3d1fb95bbd92413c8878d13aa3a1d647', max_length=255),
        ),
    ]
