# Generated by Django 3.1.2 on 2020-10-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20201025_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='schedule_signature',
            field=models.CharField(db_index=True, default='dd5dd005d6c54f5f9f865dea4441e1b5', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='signature',
            field=models.CharField(db_index=True, default='b77dbcfdffba4f628cb33aed897c3445', max_length=255),
        ),
    ]
