# Generated by Django 3.1.2 on 2020-10-27 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(db_index=True, max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'failed'), (1, 'successed')], db_index=True)),
                ('sent_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
